version: "3.9"

services:
  page_analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: page_analyzer
    restart: unless-stopped 
    ports:
      - 8000:8000
    env_file:
    - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@page_db:5432/${POSTGRES_DB}
    volumes:
      - .:/page_analyzer
    depends_on:
      - page_db
    command: sh -c "poetry run gunicorn -w 5 -b 0.0.0.0:8000 page_analyzer:app"


  page_db:
    image: postgres:16.8
    container_name: page_analyzer_db
    restart: unless-stopped 
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  postgres_data: