version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "[%(asctime)s.%(msecs)03d] [%(name)-50s] [%(module)-15s:%(lineno)-3d] [%(levelname)-8s] -> %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:

  file:
    class: "logging.handlers.RotatingFileHandler"
    level: "INFO"
    formatter: "default"
    filename: "logs/app.log"
    maxBytes: 10485760
    backupCount: 10
    encoding: "utf-8"

  console:
    class: "logging.StreamHandler"
    level: "INFO"
    formatter: "default"

root:
  level: ERROR
  handlers: ["console"]

loggers:
  page_analyzer:
    level: DEBUG
    handlers: ["console", "file"]
    propagate: false

  werkzeug:
    level: ERROR
    handlers: ["console"]
    propagate: false

  dotenv:
    level: ERROR
    handlers: ["console"]
    propagate: false

  charset_normalizer:
    level: ERROR
    handlers: ["console"]
    propagate: false

  urllib3:
    level: ERROR
    handlers: ["console"]
    propagate: false

  requests:
    level: ERROR
    handlers: ["console"]
    propagate: false